-- Revoke all privileges and drop role
ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE SELECT, INSERT, UPDATE, DELETE ON TABLES FROM coreguard_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE USAGE, SELECT ON SEQUENCES FROM coreguard_app;
REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA public FROM coreguard_app;
REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public FROM coreguard_app;
REVOKE USAGE ON SCHEMA public FROM coreguard_app;
DROP ROLE IF EXISTS coreguard_app;
