package handler

import (
	"errors"
	"fmt"
	"net/http"
	"os"
	"time"

	"elitegate/internal/container"
	"elitegate/internal/storage"

	"github.com/gin-gonic/gin"
	"github.com/google/uuid"
	"github.com/rs/zerolog"
	"gopkg.in/natefinch/lumberjack.v2"
)

type GatewayHandler struct {
	repo         *storage.GatewayRepo
	containerMgr container.ContainerManager
	logger       zerolog.Logger
}

func NewGatewayHandler(
	repo *storage.GatewayRepo,
	containerMgr container.ContainerManager,
) *GatewayHandler {
	// Ensure logs directory exists.
	if err := os.MkdirAll("logs", 0755); err != nil {
		// Ignore mkdir error and let lumberjack handle file creation failures if any
	}

	logFileWriter := &lumberjack.Logger{
		Filename:   "logs/gateway.log",
		MaxSize:    10, // megabytes
		MaxBackups: 5,
		MaxAge:     30, // days
		Compress:   true,
	}

	multi := zerolog.MultiLevelWriter(
		logFileWriter,
		zerolog.ConsoleWriter{Out: os.Stdout, TimeFormat: time.RFC3339},
	)

	logger := zerolog.New(multi).With().Timestamp().Str("component", "gateway-handler").Logger()

	return &GatewayHandler{
		repo:         repo,
		containerMgr: containerMgr,
		logger:       logger,
	}
}

type provisionRequest struct {
	ProjectID string `json:"project_id" binding:"required"`
	Plan      string `json:"plan"       binding:"required"`
}

// Provision handles POST /admin/v1/projects/:projectId/gateways
//
// Flow:
//  1. Insert a "provisioning" row in the DB so the gateway is tracked immediately.
//  2. Start the Docker container — this can take up to containerStartTimeout.
//  3. On success: mark the row "active" with real IP/port.
//     On failure: mark the row "failed" so operators can inspect or retry.
func (h *GatewayHandler) Provision(c *gin.Context) {
	var req provisionRequest
	if err := c.ShouldBindJSON(&req); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

	// externalID is the human-readable label stored in the DB and used as the
	// container name.  The DB primary key is a UUID generated by Postgres.
	externalID := "gw_" + uuid.New().String()[:8]

	h.logger.Info().
		Str("external_id", externalID).
		Str("project_id", req.ProjectID).
		Str("plan", req.Plan).
		Msg("provisioning gateway")

	// Step 1 — logical record.
	if err := h.repo.Provision(c.Request.Context(), externalID, req.ProjectID, req.Plan); err != nil {
		h.logger.Error().Err(err).Str("external_id", externalID).Msg("failed to insert gateway record")
		c.JSON(http.StatusInternalServerError, gin.H{"error": "internal server error"})
		return
	}

	// Step 2 — physical container.
	ip, port, err := h.containerMgr.Provision(c.Request.Context(), externalID, req.ProjectID, req.Plan)
	if err != nil {
		h.logger.Error().Err(err).
			Str("external_id", externalID).
			Msg("container provisioning failed")

		// Best-effort status update — don't override the original error.
		if dbErr := h.repo.UpdateStatus(c.Request.Context(), externalID, "failed"); dbErr != nil {
			h.logger.Error().Err(dbErr).
				Str("external_id", externalID).
				Msg("also failed to mark gateway as failed in DB")
		}

		c.JSON(http.StatusInternalServerError, gin.H{
			"error": fmt.Sprintf("container provisioning failed: %v", err),
		})
		return
	}

	// Step 3 — register real endpoint.
	if err := h.repo.Register(c.Request.Context(), externalID, ip, port); err != nil {
		h.logger.Error().Err(err).
			Str("external_id", externalID).
			Msg("failed to register gateway endpoint in DB")
		c.JSON(http.StatusInternalServerError, gin.H{"error": "internal server error"})
		return
	}

	h.logger.Info().
		Str("external_id", externalID).
		Str("endpoint_ip", ip).
		Str("port", port).
		Msg("gateway provisioned successfully")

	c.JSON(http.StatusAccepted, gin.H{
		"gateway_id":   externalID,
		"status":       "active",
		"endpoint_ip":  ip,
		"gateway_port": port,
	})
}

// Decommission handles DELETE /admin/v1/projects/:projectId/gateways/:gatewayId
//
// Flow:
//  1. Stop and remove the Docker container (idempotent — ok if already gone).
//  2. Soft-delete the DB row.
func (h *GatewayHandler) Decommission(c *gin.Context) {
	externalID := c.Param("gatewayId")
	if externalID == "" {
		c.JSON(http.StatusBadRequest, gin.H{"error": "gatewayId is required"})
		return
	}

	h.logger.Info().Str("external_id", externalID).Msg("decommissioning gateway")

	// Step 1 — stop and remove the container.
	if err := h.containerMgr.Decommission(c.Request.Context(), externalID); err != nil {
		h.logger.Error().Err(err).
			Str("external_id", externalID).
			Msg("failed to stop container runtime")
		c.JSON(http.StatusInternalServerError, gin.H{
			"error": fmt.Sprintf("failed to stop container: %v", err),
		})
		return
	}

	// Step 2 — soft-delete in the DB.
	if err := h.repo.Decommission(c.Request.Context(), externalID); err != nil {
		if errors.Is(err, storage.ErrGatewayNotFound) {
			// Container is gone and DB row is already gone — that's a success.
			c.JSON(http.StatusOK, gin.H{"gateway_id": externalID, "status": "decommissioned"})
			return
		}
		h.logger.Error().Err(err).
			Str("external_id", externalID).
			Msg("failed to decommission gateway in DB")
		c.JSON(http.StatusInternalServerError, gin.H{"error": "internal server error"})
		return
	}

	h.logger.Info().Str("external_id", externalID).Msg("gateway decommissioned successfully")
	c.JSON(http.StatusOK, gin.H{"gateway_id": externalID, "status": "decommissioned"})
}
