package handler

import (
	"errors"
	"fmt"
	"net/http"
	"os"
	"strings"
	"time"

	"elitegate/helper"
	"elitegate/internal/admin/middleware"
	"elitegate/internal/admin/service"
	"elitegate/internal/container"
	"elitegate/internal/model"
	"elitegate/internal/storage"

	"github.com/gin-gonic/gin"
	"github.com/google/uuid"
	"github.com/rs/zerolog"
	"gopkg.in/natefinch/lumberjack.v2"
)

type GatewayHandler struct {
	repo         *storage.GatewayRepo
	containerMgr container.ContainerManager
	logger       zerolog.Logger
	drainTimeout time.Duration
}

func NewGatewayHandler(
	repo *storage.GatewayRepo,
	containerMgr container.ContainerManager,
	drainTimeout time.Duration,
) *GatewayHandler {
	// Ensure logs directory exists.
	if err := os.MkdirAll("logs", 0755); err != nil {
		// Ignore mkdir error and let lumberjack handle file creation failures if any
	}

	logFileWriter := &lumberjack.Logger{
		Filename:   "logs/gateway.log",
		MaxSize:    10, // megabytes
		MaxBackups: 5,
		MaxAge:     30, // days
		Compress:   true,
	}

	multi := zerolog.MultiLevelWriter(
		logFileWriter,
		zerolog.ConsoleWriter{Out: os.Stdout, TimeFormat: time.RFC3339},
	)

	logger := zerolog.New(multi).With().Timestamp().Str("component", "gateway-handler").Logger()

	return &GatewayHandler{
		repo:         repo,
		containerMgr: containerMgr,
		logger:       logger,
		drainTimeout: drainTimeout,
	}
}

type provisionRequest struct {
	ProjectID string `json:"project_id" binding:"required"`
	Plan      string `json:"plan"       binding:"required"`
}

// Provision handles POST /admin/v1/projects/:projectId/gateways
//
// Flow:
//  1. Insert a "provisioning" row in the DB so the gateway is tracked immediately.
//  2. Start the Docker container — this can take up to containerStartTimeout.
//  3. On success: mark the row "active" with real IP/port.
//     On failure: mark the row "failed" so operators can inspect or retry.
func (h *GatewayHandler) Provision(c *gin.Context) {
	var req provisionRequest
	if err := c.ShouldBindJSON(&req); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

	// externalID is the human-readable label stored in the DB and used as the
	// container name.  The DB primary key is a UUID generated by Postgres.
	externalID := "gw_" + uuid.New().String()[:8]

	h.logger.Info().
		Str("external_id", externalID).
		Str("project_id", req.ProjectID).
		Str("plan", req.Plan).
		Msg("provisioning gateway")

	// Step 1 — logical record.
	if err := h.repo.Provision(c.Request.Context(), externalID, req.ProjectID, req.Plan); err != nil {
		helper.RespondInternalError(c, h.logger.With().Str("external_id", externalID).Logger(), err, "failed to insert gateway record")
		return
	}

	// Step 2 — physical container.
	ip, port, publicHost, publicPort, err := h.containerMgr.Provision(c.Request.Context(), externalID, req.ProjectID, req.Plan)
	if err != nil {
		// Best-effort status update — don't override the original error.
		if dbErr := h.repo.UpdateStatus(c.Request.Context(), externalID, "failed"); dbErr != nil {
			h.logger.Error().Err(dbErr).
				Str("external_id", externalID).
				Msg("also failed to mark gateway as failed in DB")
		}

		helper.RespondInternalError(c, h.logger.With().Str("external_id", externalID).Logger(), err, fmt.Sprintf("container provisioning failed: %v", err))
		return
	}

	// Step 3 — register real endpoint.
	if err := h.repo.Register(c.Request.Context(), externalID, ip, port, publicHost, publicPort); err != nil {
		helper.RespondInternalError(c, h.logger.With().Str("external_id", externalID).Logger(), err, "failed to register gateway endpoint in DB")
		return
	}

	h.logger.Info().
		Str("external_id", externalID).
		Str("endpoint_ip", ip).
		Str("port", port).
		Msg("gateway provisioned successfully")

	c.JSON(http.StatusAccepted, gin.H{
		"gateway_id":   externalID,
		"status":       "active",
		"endpoint_ip":  ip,
		"gateway_port": port,
		"public_host":  publicHost,
		"public_port":  publicPort,
	})
}

// Decommission handles DELETE /admin/v1/projects/:projectId/gateways/:gatewayId
//
// Flow:
//  1. Check status. If active, transition to "draining" and wait out the
//     remaining drain window (idempotent against retries — see MarkDraining).
//  2. Stop and remove the Docker container (idempotent).
//  3. Mark decommissioned / soft-delete the DB row.
//
// A gateway that never makes it past step 1 (process restart, client
// disconnect) is picked up and finished by the worker reconciler in
// cmd/worker — see ListStaleDraining.
func (h *GatewayHandler) Decommission(c *gin.Context) {
	externalID := c.Param("gatewayId")
	if externalID == "" {
		c.JSON(http.StatusBadRequest, gin.H{"error": "gatewayId is required"})
		return
	}

	// Validate format: Must be the human-readable external_id
	if !strings.HasPrefix(externalID, "gw_") {
		c.JSON(http.StatusBadRequest, gin.H{
			"error": "invalid gateway ID: please provide the external_id (e.g. 'gw_xxxx') instead of the database UUID",
		})
		return
	}

	h.logger.Info().Str("external_id", externalID).Msg("initiating graceful decommission of gateway")

	status, err := h.repo.GetGatewayStatus(c.Request.Context(), externalID)
	if err != nil {
		if errors.Is(err, storage.ErrGatewayNotFound) {
			c.JSON(http.StatusNotFound, gin.H{"error": "gateway not found"})
			return
		}
		helper.RespondInternalError(c, h.logger.With().Str("external_id", externalID).Logger(), err, "failed to retrieve gateway status")
		return
	}

	if status == "decommissioned" {
		c.JSON(http.StatusOK, gin.H{"gateway_id": externalID, "status": "decommissioned"})
		return
	}

	// Step 1 — mark draining (idempotent) and wait out whatever time is
	// left on the drain window. drainStartedAt is stable across retries,
	// so a duplicate request never shortens or restarts the wait.
	drainStartedAt, err := h.repo.MarkDraining(c.Request.Context(), externalID)
	if err != nil {
		helper.RespondInternalError(c, h.logger.With().Str("external_id", externalID).Logger(), err, "failed to initiate draining")
		return
	}

	if remaining := h.drainTimeout - time.Since(drainStartedAt); remaining > 0 {
		h.logger.Info().
			Str("external_id", externalID).
			Dur("remaining", remaining).
			Msg("draining: waiting for in-flight/upstream routing to clear")
		select {
		case <-c.Request.Context().Done():
			// The client went away mid-wait. The row is already marked
			// "draining" (excluded from ListActive), so no traffic is
			// being lost by returning here — the worker reconciler will
			// finish stopping the container and finalizing the DB row
			// once drain_stale_after elapses. We deliberately do NOT
			// treat this as an error requiring the caller to retry.
			h.logger.Warn().Str("external_id", externalID).
				Msg("client disconnected during drain wait; worker reconciler will finish decommission")
			c.JSON(http.StatusAccepted, gin.H{"gateway_id": externalID, "status": "draining"})
			return
		case <-time.After(remaining):
		}
	}

	// Step 2 — stop and remove the container gracefully.
	h.logger.Info().Str("external_id", externalID).Msg("stopping and removing gateway container runtime")
	if err := h.containerMgr.Decommission(c.Request.Context(), externalID); err != nil {
		helper.RespondInternalError(c, h.logger.With().Str("external_id", externalID).Logger(), err, fmt.Sprintf("failed to stop container: %v", err))
		return
	}

	// Step 3 — finalize decommission (soft-delete DB row).
	h.logger.Info().Str("external_id", externalID).Msg("finalizing decommission in DB")
	if err := h.repo.Decommission(c.Request.Context(), externalID); err != nil {
		if errors.Is(err, storage.ErrGatewayNotFound) {
			status, statusErr := h.repo.GetGatewayStatus(c.Request.Context(), externalID)
			if statusErr == nil && status == "decommissioned" {
				c.JSON(http.StatusOK, gin.H{"gateway_id": externalID, "status": "decommissioned"})
				return
			}
			c.JSON(http.StatusNotFound, gin.H{"error": "gateway not found"})
			return
		}
		helper.RespondInternalError(c, h.logger.With().Str("external_id", externalID).Logger(), err, "failed to decommission gateway in DB")
		return
	}
	h.logger.Info().Str("external_id", externalID).Msg("gateway decommissioned successfully")
	c.JSON(http.StatusOK, gin.H{"gateway_id": externalID, "status": "decommissioned"})
}

// List handles GET /admin/v1/projects/:projectId/gateways
func (h *GatewayHandler) List(c *gin.Context) {
	projectID := c.Param("projectId")
	if _, err := uuid.Parse(projectID); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": "invalid project ID"})
		return
	}

	page, limit, offset, err := service.ParsePaginationOffset(c.Query("page"), c.Query("limit"))
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

	h.logger.Info().Str("project_id", projectID).Msg("listing gateways for project")

	gateways, total, err := h.repo.ListByProject(c.Request.Context(), projectID, limit, offset)
	if err != nil {
		helper.RespondInternalError(c, h.logger.With().Str("project_id", projectID).Logger(), err, "failed to load gateways")
		return
	}

	c.JSON(http.StatusOK, model.PaginatedResponse[storage.GatewayRecord]{
		Items:      gateways,
		Pagination: service.BuildPagination(page, limit, total),
	})
}

// ListAllForAdmin handles GET /admin/v1/gateways
// Returns all active gateways across all projects where the authenticated admin has membership.
func (h *GatewayHandler) ListAllForAdmin(c *gin.Context) {
	adminUserIDVal, exists := c.Get(middleware.AdminUserIDKey)
	if !exists {
		c.JSON(http.StatusUnauthorized, gin.H{"error": "unauthenticated"})
		return
	}
	adminUserID, ok := adminUserIDVal.(string)
	if !ok {
		helper.RespondInternalError(c, h.logger, nil, "invalid session state")
		return
	}

	page, limit, offset, err := service.ParsePaginationOffset(c.Query("page"), c.Query("limit"))
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

	h.logger.Info().Str("admin_user_id", adminUserID).Msg("listing gateways for admin")

	gateways, total, err := h.repo.ListAllForAdmin(c.Request.Context(), adminUserID, limit, offset)
	if err != nil {
		helper.RespondInternalError(c, h.logger.With().Str("admin_user_id", adminUserID).Logger(), err, "failed to load gateways")
		return
	}

	c.JSON(http.StatusOK, model.PaginatedResponse[storage.GatewayRecord]{
		Items:      gateways,
		Pagination: service.BuildPagination(page, limit, total),
	})
}
